services:
  client:
    image: client:latest
    build:
      context: ./client
    container_name: fleetr_client
    environment:
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - fleetr_network

  server:
    image: server:latest
    build:
      context: ./server
    container_name: fleetr_server
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fleetr_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: fleetr_ngrok
    command:
      - "http"
      - "--url=sheepdog-intent-kindly.ngrok-free.app" # Set to Josh's NGROK URL
      - "http://fleetr_server:8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - fleetr_network

  postgres:
    image: postgres:latest
    container_name: fleetr_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - fleetr_network

  nginx:
    image: nginx:latest
    container_name: fleetr_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    restart: always
    networks:
      - fleetr_network

networks:
  fleetr_network:
    driver: bridge
